CREATE TABLE wykladowcy(
wykladowca_id number(6) primary key,
imie varchar2(20) NOT NULL,   
nazwisko varchar2(30) NOT NULL,
stawka decimal(5,2)
);
CREATE TABLE kursanci(
kursant_id number(6) PRIMARY KEY,
imie varchar2(20) NOT NULL,
nazwisko varchar2(30) NOT NULL
);
CREATE TABLE rodzaje(
rodzaj_id number(3) primary key,
nazwa varchar2(30) NOT NULL,
godz number(3) NOT NULL,
cena decimal(6,2)
);
CREATE TABLE kursy(
kurs_id number(6)primary key,
rodzaj_id number(6) NOT NULL,
wykladowca_id number(6)
);
CREATE TABLE umowy(
umowa_id number(6) primary key,
kursant_id number(6),
kurs_id number(6),
miasto varchar(20)
);
--------------- MODELOWANIE ZWI•ZK”W-----------------------------

ALTER TABLE kursy ADD CONSTRAINT kursy_rodzaje_fkey FOREIGN KEY (rodzaj_id) REFERENCES rodzaje(rodzaj_id);
ALTER TABLE kursy ADD CONSTRAINT kursy_wykladowcy_fkey FOREIGN KEY (wykladowca_id) REFERENCES wykladowcy(wykladowca_id);
----------------


INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (1, 'PRZEMYS£AW', 'KRAJEWSKI', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (2, 'LEO', 'ADAMSKI', 90);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (3, 'NATANIEL', 'SIKORSKI', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (4, 'RYSZARD', 'MR”Z', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (5, 'FELIKS', 'LASKOWSKI', 70);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (6, 'MAREK', 'ZI”£KOWSKI', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (7, 'RADOS£AW', 'GAJEWSKI', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (8, 'KONRAD', 'SZULC', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (9, 'ALEX', 'MAKOWSKI', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (10, 'DORIAN', 'BARANOWSKI', 70);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (11, 'JULIUSZ', 'CZERWI—SKI', 70);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (12, 'JEREMI', 'SZYMCZAK', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (13, 'ALEKS', 'PRZYBYLSKI', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (14, 'REMIGIUSZ', 'KACZMARCZYK', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (15, 'FLORIAN', 'BRZEZI—SKI', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (16, 'SAMUEL', 'B£ASZCZYK', 90);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (17, 'ARKADIUSZ', 'ANDRZEJEWSKI', 90);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (18, 'GRACJAN', 'CIEåLAK', 80);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (19, 'ALBERT', 'BOROWSKI', 100);


-----
INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1, 'LEOKADIA', 'NOWAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (2, 'NELA', 'KOWALSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (3, 'EMMA', 'WIåNIEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (4, 'JULITA', 'W”JCIK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (5, 'OKTAWIA', 'KOWALCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (6, 'PAULA', 'KAMI—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (7, 'REGINA', 'LEWANDOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (8, 'SABINA', 'ZIELI—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (9, 'SANDRA', 'SZYMA—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (10, 'FELICJA', 'D•BROWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (11, 'KONSTANCJA', 'WOèNIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (12, 'MELANIA', 'KOZ£OWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (13, 'MIROS£AWA', 'JANKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (14, 'SOFIA', 'MAZUR');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (15, 'BRONIS£AWA', 'KWIATKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (16, 'CELINA', 'WOJCIECHOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (17, 'GENOWEFA', 'KRAWCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (18, 'IZABELLA', 'KACZMAREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (19, 'JAåMINA', 'PIOTROWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (20, 'MAGDA', 'GRABOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (21, 'MARIE', 'PAW£OWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (22, 'MARIKA', 'MICHALSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (23, 'OLIVIA', 'KR”L');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (24, 'ROKSANA', 'ZAJ•C');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (25, 'WALENTYNA', 'WIECZOREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (26, 'WIES£AWA', 'JAB£O—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (27, 'AURORA', 'WR”BEL');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (28, 'DAGMARA', 'NOWAKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (29, 'ELENA', 'MAJEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (30, 'ELIZABETH', 'OLSZEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (31, 'HONORATA', 'ADAMCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (32, 'ILONA', 'JAWORSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (33, 'JAGNA', 'MALINOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (34, 'JULIANNA', 'ST PIE—');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (35, 'LUIZA', 'DUDEK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (36, 'VIKTORIA', 'G”RSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (37, 'W£ADYS£AWA', 'NOWICKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (38, 'ØANETA', 'WITKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (39, 'ADA', 'PAWLAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (40, 'ELEONORA', 'SIKORA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (41, 'ELWIRA', 'WALCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (42, 'EULALIA', 'RUTKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (43, 'EVA', 'MICHALAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (44, 'FILOMENA', 'SZEWCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (45, 'FLORENTYNA', 'OSTROWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (46, 'HENRYKA', 'BARAN');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (47, 'INGA', 'TOMASZEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (48, 'LEA', 'ZALEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (49, 'LILA', 'PIETRZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (50, 'LILLA', 'WR”BLEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (51, 'LIVIA', 'JASI—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (52, 'LUDWIKA', 'MARCINIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (53, 'MALINA', 'JAKUBOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (54, 'MARCELA', 'SADOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (55, 'MARCJANNA', 'ZAWADZKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (56, 'MIRA', 'DUDA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (57, 'NAOMI', 'W£ODARCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (58, 'NEL', 'B•K');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (59, 'NICOLA', 'CHMIELEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (60, 'ROMA', 'BORKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (61, 'ROSE', 'WILK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (62, 'VIOLETTA', 'SOKO£OWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (63, 'WALERIA', 'SZCZEPA—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (64, 'WIOLETA', 'SAWICKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (65, 'ALDONA', 'LIS');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (66, 'AMANDA', 'KUCHARSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (67, 'ANDØELIKA', 'MACIEJEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (68, 'BERNADETA', 'KALINOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (69, 'BERNADETTA', 'MAZUREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (70, 'DOBROS£AWA', 'WYSOCKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (71, 'DOMICELA', 'KUBIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (72, 'ESTERA', 'KO£ODZIEJ');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (73, 'FLORA', 'CZARNECKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (74, 'GLORIA', 'KAèMIERCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (75, 'HALSZKA', 'URBA—SKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (76, 'HIACYNTA', 'SOBCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (77, 'JOWITA', 'G£OWACKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (78, 'KLEMENTYNA', 'KRAJEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (79, 'LAILA', 'KRUPA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (80, 'LORENA', 'SIKORSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (81, 'MARIETTA', 'ZAKRZEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (82, 'MIRIAM', 'WASILEWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (83, 'NAWOJKA', 'ZI”£KOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (84, 'OLIMPIA', 'LASKOWSKA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (85, 'OTYLIA', 'GAJEWSKA');

-------------------------
INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (1, 'angielski', 80, 1200);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (2, 'w≥oski', 90, 890);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (3, 'francuski', 80, 1200);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (4, 'grecki', 70, 970);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (5, 'japoÒski', 60, 670);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (6, 'czeski', 70, 940);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (7, 'rosyjski', 80, 850);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (8, 'niemiecki', 80, 1100);
-------------------

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (1, 1, 1);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (2, 2, 2);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (3, 2, 2);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (4, 3, 3);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (5, 4, 4);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (6, 5, 6);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (7, 6, 7);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (8, 7, 9);
---------------------------

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (1, 1, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (2, 2, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (3, 3, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (4, 4, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (5, 5, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (6, 6, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (7, 7, 1, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (8, 8, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (9, 9, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (10, 10, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (11, 11, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (12, 12, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (13, 13, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (14, 14, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (15, 15, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (16, 16, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (17, 17, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (18, 18, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (19, 19, 2, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (20, 20, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (21, 21, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (22, 22, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (23, 23, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (24, 24, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (25, 25, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (26, 26, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (27, 27, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (28, 28, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (29, 29, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (30, 30, 3, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (31, 31, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (32, 32, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (33, 33, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (34, 34, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (35, 35, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (36, 36, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (37, 37, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (38, 38, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (39, 39, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (40, 40, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (41, 41, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (42, 42, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (43, 43, 4, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (44, 44, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (45, 45, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (46, 46, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (47, 47, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (48, 48, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (49, 49, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (50, 50, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (51, 51, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (52, 52, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (53, 53, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (54, 54, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (55, 55, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (56, 56, 5, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (57, 57, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (58, 58, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (59, 59, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (60, 60, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (61, 61, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (62, 62, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (63, 63, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (64, 64, 6, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (65, 65, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (66, 66, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (67, 67, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (68, 68, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (69, 69, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (70, 70, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (71, 71, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (72, 72, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (73, 73, 7, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (74, 74, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (75, 75, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (76, 76, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (77, 77, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (78, 78, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (79, 79, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (80, 80, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (81, 81, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (82, 82, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (83, 83, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (84, 84, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (85, 85, 8, 'BYDGOSZCZ');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (86, 1000, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (87, 1001, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (88, 1002, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (89, 1003, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (90, 1004, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (91, 1005, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (92, 1006, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (93, 1007, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (94, 1008, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (95, 1009, 101, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (96, 1010, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (97, 1011, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (98, 1012, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (99, 1013, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (100, 1014, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (101, 1015, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (102, 1016, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (103, 1017, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (104, 1018, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (105, 1019, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (106, 1020, 102, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (107, 1021, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (108, 1022, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (109, 1023, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (110, 1024, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (111, 1025, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (112, 1026, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (113, 1027, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (114, 1028, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (115, 1029, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (116, 1030, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (117, 1031, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (118, 1032, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (119, 1033, 103, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (120, 1034, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (121, 1035, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (122, 1036, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (123, 1037, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (124, 1038, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (125, 1039, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (126, 1040, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (127, 1041, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (128, 1042, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (129, 1043, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (130, 1044, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (131, 1045, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (132, 1046, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (133, 1047, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (134, 1048, 104, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (135, 1049, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (136, 1050, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (137, 1051, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (138, 1052, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (139, 1053, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (140, 1054, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (141, 1055, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (142, 1056, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (143, 1057, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (144, 1058, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (145, 1059, 105, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (146, 1060, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (147, 1061, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (148, 1062, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (149, 1063, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (150, 1064, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (151, 1065, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (152, 1066, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (153, 1067, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (154, 1068, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (155, 1069, 106, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (156, 1070, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (157, 1071, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (158, 1072, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (159, 1073, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (160, 1074, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (161, 1075, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (162, 1076, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (163, 1077, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (164, 1078, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (165, 1079, 107, 'SZCZECIN');

INSERT INTO UMOWY (UMOWA_ID, KURSANT_ID, KURS_ID, MIASTO) 
VALUES (166, 1080, 107, 'SZCZECIN');


commit;

select * from kursanci;

create  database link dblinkFilia using 'baza11b';

create synonym kursanciF for kursanci@dblinkFilia;

create synonym wykladowcyF for wykladowcy@dblinkFilia;

select * from kursanciF;

create view wykladowcyAll as 
select imie, nazwisko from wykladowcy
UNION
select imie, nazwisko from wykladowcyF
order by nazwisko;

select * from wykladowcyAll;

select * from wykladowcyF order by nazwisko;

create view kursanciAll as 
select imie, nazwisko from kursanci
UNION
select imie, nazwisko from kursanciF
order by nazwisko;

create synonym kursyF for kursy@dblinkFilia;

CREATE VIEW kursy_definicje_v AS
SELECT kurs_id, rodzaj_id, wykladowca_id FROM kursy
UNION ALL
SELECT kurs_id, rodzaj_id, wykladowca_id FROM kursyF;

CREATE OR REPLACE VIEW kursyAll AS
SELECT 
    r.nazwa AS nazwa_kursu,
    w.imie || ' ' || w.nazwisko AS prowadzacy,
    (SELECT COUNT(*) FROM umowy u WHERE u.kurs_id = k.kurs_id) AS liczba_uczestnikow
FROM kursySiedziba k
JOIN wykladowcySiedziba w ON k.wykladowca_id = w.wykladowca_id
JOIN rodzajeSiedziba r ON k.rodzaj_id = r.rodzaj_id

UNION ALL

SELECT 
    rf.nazwa AS nazwa_kursu,
    wf.imie || ' ' || wf.nazwisko AS prowadzacy,

    (SELECT COUNT(*) FROM umowy u WHERE u.kurs_id = kf.kurs_id) AS liczba_uczestnikow
FROM kursyFilia kf
JOIN wykladowcyFilia wf ON kf.wykladowca_id = wf.wykladowca_id
JOIN rodzajeFilia rf ON kf.rodzaj_id = rf.rodzaj_id;

SELECT SUM(r_all.cena) AS przychod_calkowity
FROM umowy u
JOIN (
    SELECT k.kurs_id, r.cena 
    FROM kursySiedziba k
    JOIN rodzajeSiedziba r ON k.rodzaj_id = r.rodzaj_id
    UNION ALL
    SELECT kf.kurs_id, rf.cena 
    FROM kursyFilia kf
    JOIN rodzajeFilia rf ON kf.rodzaj_id = rf.rodzaj_id
) r_all ON u.kurs_id = r_all.kurs_id;

SELECT SUM(koszty_v.godz * koszty_v.stawka) AS koszty_calkowite
FROM (

    SELECT r.godz, w.stawka
    FROM kursySiedziba k
    JOIN rodzajeSiedziba r ON k.rodzaj_id = r.rodzaj_id
    JOIN wykladowcySiedziba w ON k.wykladowca_id = w.wykladowca_id
    
    UNION ALL
    

    SELECT rf.godz, wf.stawka
    FROM kursyFilia kf
    JOIN rodzajeFilia rf ON kf.rodzaj_id = rf.rodzaj_id
    JOIN wykladowcyFilia wf ON kf.wykladowca_id = wf.wykladowca_id
) koszty_v;


SELECT SUM(wynik.przychod - wynik.koszt) AS zysk_ogolem
FROM (

    SELECT 
        (SELECT COUNT(*) FROM umowy u WHERE u.kurs_id = k.kurs_id) * r.cena AS przychod,
        (r.godz * w.stawka) AS koszt
    FROM kursySiedziba k
    JOIN rodzajeSiedziba r ON k.rodzaj_id = r.rodzaj_id
    JOIN wykladowcySiedziba w ON k.wykladowca_id = w.wykladowca_id
    
    UNION ALL
    

    SELECT 
        (SELECT COUNT(*) FROM umowy u WHERE u.kurs_id = kf.kurs_id) * rf.cena AS przychod,
        (rf.godz * wf.stawka) AS koszt
    FROM kursyFilia kf
    JOIN rodzajeFilia rf ON kf.rodzaj_id = rf.rodzaj_id
    JOIN wykladowcyFilia wf ON kf.wykladowca_id = wf.wykladowca_id
) wynik;

