CREATE TABLE wykladowcy(
wykladowca_id number(6) primary key,
imie varchar2(20) NOT NULL,   
nazwisko varchar2(30) NOT NULL,
stawka decimal(5,2)
);
CREATE TABLE kursanci(
kursant_id number(6) PRIMARY KEY,
imie varchar2(20) NOT NULL,
nazwisko varchar2(30) NOT NULL
);
CREATE TABLE rodzaje(
rodzaj_id number(3) primary key,
nazwa varchar2(30) NOT NULL,
godz number(3) NOT NULL,
cena decimal(6,2)
);
CREATE TABLE kursy(
kurs_id number(6)primary key,
rodzaj_id number(6) NOT NULL,
wykladowca_id number(6)
);

--------------- MODELOWANIE ZWI•ZK”W-----------------------------

ALTER TABLE kursy ADD CONSTRAINT kursy_rodzaje_fkey FOREIGN KEY (rodzaj_id) REFERENCES rodzaje(rodzaj_id);
ALTER TABLE kursy ADD CONSTRAINT kursy_wykladowcy_fkey FOREIGN KEY (wykladowca_id) REFERENCES wykladowcy(wykladowca_id);
----------------


INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1000, 'ANTONI', 'NOWAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1001, 'JAN', 'KOWALSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1002, 'ALEKSANDER', 'WIåNIEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1003, 'JAKUB', 'W”JCIK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1004, 'FRANCISZEK', 'KOWALCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1005, 'SZYMON', 'KAMI—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1006, 'FILIP', 'LEWANDOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1007, 'MIKO£AJ', 'D•BROWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1008, 'LEON', 'ZIELI—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1009, 'STANIS£AW', 'SZYMA—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1010, 'WOJCIECH', 'WOèNIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1011, 'ADAM', 'KOZ£OWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1012, 'KACPER', 'JANKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1013, 'TYMON', 'MAZUR');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1014, 'NIKODEM', 'WOJCIECHOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1015, 'MARCEL', 'KWIATKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1016, 'IGNACY', 'KRAWCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1017, 'MICHA£', 'KACZMAREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1018, 'WIKTOR', 'PIOTROWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1019, 'IGOR', 'GRABOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1020, 'OLIWIER', 'ZAJ•C');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1021, 'MAKSYMILIAN', 'PAW£OWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1022, 'PIOTR', 'MICHALSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1023, 'TYMOTEUSZ', 'KR”L');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1024, 'MI£OSZ', 'NOWAKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1025, 'OSKAR', 'WIECZOREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1026, 'JULIAN', 'WR”BEL');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1027, 'BARTOSZ', 'JAB£O—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1028, 'DAWID', 'ADAMCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1029, 'MATEUSZ', 'DUDEK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1030, 'KRZYSZTOF', 'MAJEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1031, 'GABRIEL', 'NOWICKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1032, 'KAROL', 'OLSZEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1033, 'ALAN', 'ST PIE—');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1034, 'DOMINIK', 'JAWORSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1035, 'HUBERT', 'MALINOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1036, 'TOMASZ', 'PAWLAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1037, 'MACIEJ', 'G”RSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1038, 'FABIAN', 'WITKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1039, 'BRUNO', 'SIKORA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1040, 'PAWE£', 'WALCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1041, 'NATAN', 'RUTKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1042, 'KSAWERY', 'BARAN');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1043, 'KAMIL', 'MICHALAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1044, 'BORYS', 'SZEWCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1045, 'BART£OMIEJ', 'OSTROWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1046, 'ARTUR', 'TOMASZEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1047, 'TADEUSZ', 'PIETRZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1048, 'PATRYK', 'ZALEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1049, 'CEZARY', 'DUDA');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1050, 'KAJETAN', 'WR”BLEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1051, 'KUBA', 'JASI—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1052, 'ADRIAN', 'MARCINIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1053, 'OLAF', 'B•K');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1054, 'HENRYK', 'SADOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1055, 'GRZEGORZ', 'ZAWADZKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1056, 'SEBASTIAN', 'JAKUBOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1057, 'DANIEL', 'WILK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1058, 'ERYK', 'CHMIELEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1059, 'KORNEL', 'W£ODARCZYK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1060, 'KRYSTIAN', 'BORKOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1061, 'WITOLD', 'SOKO£OWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1062, 'KAZIMIERZ', 'SZCZEPA—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1063, 'J”ZEF', 'SAWICKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1064, 'RAFA£', 'LIS');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1065, 'TEODOR', 'KUCHARSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1066, 'MILAN', 'MAZUREK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1067, 'JERZY', 'KUBIAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1068, 'STEFAN', 'KALINOWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1069, 'TOBIASZ', 'WYSOCKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1070, 'MIESZKO', 'MACIEJEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1071, '£UKASZ', 'CZARNECKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1072, 'LEONARD', 'KO£ODZIEJ');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1073, 'EMIL', 'URBA—SKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1074, 'GUSTAW', 'KAèMIERCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1075, 'MARCIN', 'SOBCZAK');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1076, 'DAMIAN', 'KONIECZNY');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1077, 'OLIVIER', 'G£OWACKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1078, 'ROBERT', 'WASILEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1079, 'B£AØEJ', 'ZAKRZEWSKI');

INSERT INTO KURSANCI (KURSANT_ID, IMIE, NAZWISKO) 
VALUES (1080, 'KONSTANTY', 'KRUPA');

--------------------------------------------


INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (101, 'SONIA', 'SZULC', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (102, 'VICTORIA', 'MAKOWSKA', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (103, 'ZYTA', 'BRZEZI—SKA', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (104, 'ØYWIA', 'PRZYBYLSKA', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (105, 'MARIA', 'BARANOWSKA', 110);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (106, 'ANNA', 'KACZMARCZYK', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (107, 'ZOFIA', 'SZYMCZAK', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (108, 'EWA', 'ADAMSKA', 130);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (109, 'MAGDALENA', 'B£ASZCZYK', 150);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (110, 'HELENA', 'BOROWSKA', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (111, 'KATARZYNA', 'G”RECKA', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (112, 'WIKTORIA', 'KANIA', 100);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (113, 'BARBARA', 'SZCZEPANIAK', 120);

INSERT INTO WYKLADOWCY (WYKLADOWCA_ID, IMIE, NAZWISKO, STAWKA) 
VALUES (114, 'ROMANA', 'MR”Z', 130);


----------------------------------------
INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (101, 'bazy danych Oracle', 120, 1950);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (102, 'javascript', 130, 1800);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (103, 'python', 100, 2400);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (104, 'sql server', 90, 2300);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (105, 'java ', 100, 2100);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (106, 'cisco', 120, 2800);

INSERT INTO RODZAJE (RODZAJ_ID, NAZWA, GODZ, CENA) 
VALUES (107, 'GIS', 90, 1700);


-------------------------------------------


INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (101, 102, 103);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (102, 102, 106);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (103, 103, 102);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (104, 104, 110);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (105, 105, 111);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (106, 106, 101);

INSERT INTO KURSY (KURS_ID, RODZAJ_ID, WYKLADOWCA_ID) 
VALUES (107, 107, 114);

commit;

select * from kursanci;